F
======================================================================
FAIL: test_handle_stop (__main__.TestStringMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_3.py", line 9, in test_handle_stop
    self.assertEqual(functions.handle_stop("asd"), "Adios asd")
AssertionError: None != 'Adios asd'

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)