F
======================================================================
FAIL: test_welcome (__main__.TestStringMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\test_1.py", line 9, in test_welcome
    self.assertEqual(functions.greet(time=21, name="Anibal"), "¡Buenas noches Anibal!")
AssertionError: None != '¡Buenas noches Anibal!'

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)