F
======================================================================
FAIL: test_start (__main__.TestStringMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\test_5.py", line 9, in test_start
    self.assertEqual(functions.start_game("ohce Anibal"), "Anibal")
AssertionError: None != 'Anibal'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)