F
======================================================================
FAIL: test_handle_word (__main__.TestStringMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_2.py", line 9, in test_handle_word
    self.assertEqual(functions.handle_word("hola"), "aloh")
AssertionError: None != 'aloh'

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)